### ISSUE TITLE
How to create a workflow that opens an application with a parameter?

### ISSUE THREAD

**Issue by sejoharp** [rossmacarthur/powerpack#7]
Hello, thanks for this lib. I already use it for searching and opening bookmarks and it works great.

I would like to create a workflow, that opens a directory with intellij or vscode. 
e.g. `idea /path/to/repository` or `IntelliJ IDEA Ultimate.app /path/to/repository`

The Modifier-class seems to change arguments, but I don't see how I can specifly which application/command to execute. When I look at other workflows, it looks like I have to change the info.plist.

Could you help me out? Do you have an example?

thanks in advance and best regards
Joscha

**Comment by rossmacarthur** [comment]
Hi @sejoharp, a script filter workflow might not be the best option for this 🤔. I'm guessing you've tried all the built-in Actions provided by Alfred for workflows?

**Comment by sejoharp** [comment]
Hi @rossmacarthur, Thanks for your answer. I did not try to create a simple workflow and looked at the plist file.

I found this example: https://github.com/jason0x43/alfred-toggl
I‘ll try to build my use case this way.
